version: '3'
services:
    dummy:
        build:
            context: ./server
            dockerfile: ./Dockerfile
            args:
                port: 3001
                project: //cmd/dummy:dummy
        ports:
            - 8001:3001
        restart: on-failure
        volumes:
            - dummy_vol:/go/src/mono/server
        networks:
            - mono_net
    dummer:
        build:
            context: ./server
            dockerfile: ./Dockerfile
            args:
                dummy_host: 'dummy:3001'
                port: 3002
                project: //cmd/dummer:dummer
        ports:
            - 8002:3002
        restart: on-failure
        volumes:
            - dummer_vol:/go/src/mono/server
        networks:
            - mono_net

volumes:
    dummy_vol:
    dummer_vol:

networks:
    mono_net:
        driver: bridge

